# Generated by Django 5.2.8 on 2025-12-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='username',
            field=models.CharField(default='', help_text='Username of the user who took this assessment', max_length=150),
        ),
    ]
