# Generated by Django 5.2.8 on 2025-12-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_call_chat_chatmessage_counsellorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether OTP was used for registration'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='When OTP was used', null=True),
        ),
    ]
