# Generated by Django 5.2.8 on 2025-12-05 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assessment_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(help_text='Entry title', max_length=200)),
                ('emoji', models.CharField(blank=True, help_text='Emoji or short label', max_length=32)),
                ('date', models.DateField(help_text='Entry date')),
                ('write_something', models.TextField(help_text='Journal content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When entry was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When entry was last updated')),
                ('user', models.ForeignKey(help_text='Owner of the journal entry', on_delete=django.db.models.deletion.CASCADE, related_name='my_journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My Journal Entry',
                'verbose_name_plural': 'My Journal Entries',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.DeleteModel(
            name='WellnessJournalEntry',
        ),
    ]
