# Generated by Django 5.2.8 on 2025-12-05 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_myjournal_delete_wellnessjournalentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(choices=[('box', 'Box Breathing'), ('478', '4-7-8 Breathing'), ('deep', 'Deep Breathing'), ('calm', 'Calm Breathing'), ('custom', 'Custom')], default='deep', help_text='Breathing technique used', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Total duration of the session in seconds')),
                ('cycles_completed', models.PositiveIntegerField(default=0, help_text='Number of breathing cycles completed')),
                ('inhale_seconds', models.PositiveSmallIntegerField(default=4, help_text='Inhale duration in seconds')),
                ('hold_seconds', models.PositiveSmallIntegerField(default=4, help_text='Hold duration in seconds')),
                ('exhale_seconds', models.PositiveSmallIntegerField(default=4, help_text='Exhale duration in seconds')),
                ('mood_before', models.CharField(blank=True, help_text="User's mood before the session", max_length=20)),
                ('mood_after', models.CharField(blank=True, help_text="User's mood after the session", max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the session')),
                ('completed', models.BooleanField(default=True, help_text='Whether the session was completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session was recorded')),
                ('user', models.ForeignKey(help_text='User who completed this breathing session', on_delete=django.db.models.deletion.CASCADE, related_name='breathing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Breathing Session',
                'verbose_name_plural': 'Breathing Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
