# Generated by Django 5.2.8 on 2025-12-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_breathingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathingsession',
            name='username',
            field=models.CharField(default='', help_text='Username at time of session', max_length=150),
        ),
        migrations.AlterField(
            model_name='breathingsession',
            name='hold_seconds',
            field=models.PositiveSmallIntegerField(default=0, help_text='Hold duration in seconds'),
        ),
    ]
