# Generated by Django 5.2.8 on 2025-12-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_breathingsession_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breathingsession',
            name='mood_after',
        ),
        migrations.RemoveField(
            model_name='breathingsession',
            name='mood_before',
        ),
        migrations.RemoveField(
            model_name='breathingsession',
            name='notes',
        ),
    ]
