# Generated by Django 5.2.8 on 2025-12-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_breathingsession_mood_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The affirmation/quote text')),
                ('author', models.CharField(blank=True, help_text='Author of the quote (optional)', max_length=100)),
                ('category', models.CharField(blank=True, default='general', help_text='Category (e.g., motivation, calm, self-love)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this affirmation is visible to users')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the affirmation was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the affirmation was last updated')),
            ],
            options={
                'verbose_name': 'Affirmation',
                'verbose_name_plural': 'Affirmations',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
