# Generated by Django 4.2.7 on 2025-11-19 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('video', 'Video Call'), ('voice', 'Voice Call')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ringing', 'Ringing'), ('active', 'Active'), ('ended', 'Ended'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Call duration in seconds')),
                ('notes', models.TextField(blank=True, help_text='Post-call notes or summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AlterModelOptions(
            name='moodlog',
            options={'ordering': ('-recorded_at', '-id')},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='moodlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingsession',
            name='counsellor',
            field=models.ForeignKey(blank=True, limit_choices_to={'counsellorprofile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsellor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wellnessjournalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', '-created_at'], name='api_chat_user_id_53a809_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['counsellor', '-created_at'], name='api_chat_counsel_803a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['status', '-created_at'], name='api_chat_status_2a3577_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['counsellor', 'status'], name='api_chat_counsel_b6e460_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='api_chatmes_chat_id_5d8e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-created_at'], name='api_chatmes_sender__d0513b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', '-created_at'], name='api_chatmes_chat_id_c99b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='moodlog',
            index=models.Index(fields=['user', '-recorded_at'], name='api_moodlog_user_id_90bd77_idx'),
        ),
        migrations.AddIndex(
            model_name='moodlog',
            index=models.Index(fields=['user', 'value', '-recorded_at'], name='api_moodlog_user_id_76d00a_idx'),
        ),
        migrations.AddIndex(
            model_name='upcomingsession',
            index=models.Index(fields=['user', 'start_time'], name='api_upcomin_user_id_559aac_idx'),
        ),
        migrations.AddIndex(
            model_name='upcomingsession',
            index=models.Index(fields=['counsellor', 'start_time'], name='api_upcomin_counsel_e1352f_idx'),
        ),
        migrations.AddIndex(
            model_name='upcomingsession',
            index=models.Index(fields=['start_time', 'is_confirmed'], name='api_upcomin_start_t_91efa1_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='api_userpro_user_id_ea9cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='wellnessjournalentry',
            index=models.Index(fields=['user', '-created_at'], name='api_wellnes_user_id_d36e33_idx'),
        ),
        migrations.AddIndex(
            model_name='wellnessjournalentry',
            index=models.Index(fields=['user', 'entry_type', '-created_at'], name='api_wellnes_user_id_161039_idx'),
        ),
        migrations.AddIndex(
            model_name='wellnesstask',
            index=models.Index(fields=['user', 'category', 'is_completed'], name='api_wellnes_user_id_627049_idx'),
        ),
        migrations.AddIndex(
            model_name='wellnesstask',
            index=models.Index(fields=['user', '-created_at'], name='api_wellnes_user_id_d281f4_idx'),
        ),
        migrations.AddField(
            model_name='call',
            name='counsellor',
            field=models.ForeignKey(blank=True, limit_choices_to={'counsellorprofile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsellor_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['user', '-created_at'], name='api_call_user_id_7ec5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['counsellor', '-created_at'], name='api_call_counsel_d24a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status', '-created_at'], name='api_call_status_c54384_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['counsellor', 'status'], name='api_call_counsel_1aa668_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['scheduled_at', 'status'], name='api_call_schedul_bbb190_idx'),
        ),
    ]
