# Generated by Django 4.2.7 on 2025-11-19 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_call_alter_chat_options_alter_moodlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='counsellor',
            field=models.ForeignKey(blank=True, help_text='Counselor assigned to this chat', limit_choices_to={'counsellorprofile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the chat was created'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When the chat ended (completed or cancelled)', null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='initial_message',
            field=models.TextField(blank=True, help_text='Initial message from user when creating the chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the chat became active (counselor accepted)', null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', help_text='Current status of the chat', max_length=20),
        ),
        migrations.AlterField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(help_text='User who initiated this chat', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['status', 'counsellor'], name='chat_queued_idx'),
        ),
    ]
