# Generated by Django 4.2.7 on 2025-11-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_chat_options_alter_chat_counsellor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='client_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generated UUID for deduplication', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'client_message_id'], name='chat_client_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'client_message_id'], name='sender_client_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id__isnull', False)), fields=('sender', 'client_message_id'), name='unique_client_message_per_sender'),
        ),
    ]
