# Generated by Django 5.2.8 on 2025-11-20 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_chatmessage_client_message_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Call', 'verbose_name_plural': 'Calls'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('created_at', 'id'), 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='counsellorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Counselor Profile', 'verbose_name_plural': 'Counselor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Doctor Profile', 'verbose_name_plural': 'Doctor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ('-created_at',), 'verbose_name': 'Email OTP', 'verbose_name_plural': 'Email OTPs'},
        ),
        migrations.AlterModelOptions(
            name='guidanceresource',
            options={'ordering': ('resource_type', 'title'), 'verbose_name': 'Guidance Resource', 'verbose_name_plural': 'Guidance Resources'},
        ),
        migrations.AlterModelOptions(
            name='meditationsession',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Meditation Session', 'verbose_name_plural': 'Meditation Sessions'},
        ),
        migrations.AlterModelOptions(
            name='mindcarebooster',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Mind Care Booster', 'verbose_name_plural': 'Mind Care Boosters'},
        ),
        migrations.AlterModelOptions(
            name='moodlog',
            options={'ordering': ('-recorded_at', '-id'), 'verbose_name': 'Mood Log', 'verbose_name_plural': 'Mood Logs'},
        ),
        migrations.AlterModelOptions(
            name='musictrack',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Music Track', 'verbose_name_plural': 'Music Tracks'},
        ),
        migrations.AlterModelOptions(
            name='supportgroup',
            options={'ordering': ('name',), 'verbose_name': 'Support Group', 'verbose_name_plural': 'Support Groups'},
        ),
        migrations.AlterModelOptions(
            name='supportgroupmembership',
            options={'ordering': ('-joined_at',), 'verbose_name': 'Support Group Membership', 'verbose_name_plural': 'Support Group Memberships'},
        ),
        migrations.AlterModelOptions(
            name='upcomingsession',
            options={'ordering': ('start_time', 'id'), 'verbose_name': 'Upcoming Session', 'verbose_name_plural': 'Upcoming Sessions'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='wellnessjournalentry',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Wellness Journal Entry', 'verbose_name_plural': 'Wellness Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='wellnesstask',
            options={'ordering': ('category', 'order', 'id'), 'verbose_name': 'Wellness Task', 'verbose_name_plural': 'Wellness Tasks'},
        ),
        migrations.AlterField(
            model_name='call',
            name='call_type',
            field=models.CharField(choices=[('video', 'Video Call'), ('voice', 'Voice Call')], default='video', help_text='Type of call (video or voice)', max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='counsellor',
            field=models.ForeignKey(blank=True, help_text='Counselor for this call', limit_choices_to={'counsellorprofile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsellor_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='call',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When call was created'),
        ),
        migrations.AlterField(
            model_name='call',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When call ended', null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When call is scheduled', null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When call started', null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ringing', 'Ringing'), ('active', 'Active'), ('ended', 'Ended'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the call', max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When call was last updated'),
        ),
        migrations.AlterField(
            model_name='call',
            name='user',
            field=models.ForeignKey(help_text='User who initiated the call', on_delete=django.db.models.deletion.CASCADE, related_name='user_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='counsellor',
            field=models.ForeignKey(blank=True, help_text='Counselor assigned to this chat (null for queued chats)', limit_choices_to={'counsellorprofile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the chat became active (counselor accepted or user sent message)', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='chat',
            field=models.ForeignKey(help_text='Chat this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chat'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When message was created'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(help_text='Message content'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When message was last updated'),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text="Counselor's biography"),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When profile was created'),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether counselor is currently available'),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='List of languages spoken'),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0.00 to 5.00)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text="Counselor's area of specialization", max_length=200),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When profile was last updated'),
        ),
        migrations.AlterField(
            model_name='counsellorprofile',
            name='user',
            field=models.OneToOneField(help_text='Associated Django User (must be a counselor)', on_delete=django.db.models.deletion.CASCADE, related_name='counsellorprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text="Doctor's biography"),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When profile was created'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether doctor is currently available'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='List of languages spoken'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Medical license number', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0.00 to 5.00)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text="Doctor's area of specialization", max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When profile was last updated'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(help_text='Associated Django User (must be a doctor)', on_delete=django.db.models.deletion.CASCADE, related_name='doctorprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of verification attempts'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(help_text='OTP code', max_length=6),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When OTP was created'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(help_text='Email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(help_text='When OTP expires'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether OTP is verified'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password reset')], help_text='OTP purpose', max_length=32),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='token',
            field=models.CharField(help_text='Unique verification token', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When OTP was verified', null=True),
        ),
        migrations.AlterField(
            model_name='guidanceresource',
            name='category',
            field=models.CharField(blank=True, help_text='Resource category', max_length=120),
        ),
        migrations.AlterField(
            model_name='guidanceresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When resource was created'),
        ),
        migrations.AlterField(
            model_name='guidanceresource',
            name='duration',
            field=models.CharField(blank=True, help_text='Resource duration', max_length=40),
        ),
        migrations.AlterField(
            model_name='guidanceresource',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether resource is featured'),
        ),
        migrations.AlterField(
            model_name='guidanceresource',
            name='media_url',
            field=models.URLField(blank=True, help_text='Media URL'),
        ),
        migrations.AlterField(
            model_name='guidanceresource',
            name='resource_type',
            field=models.CharField(choices=[('article', 'Article'), ('talk', 'Expert Talk'), ('podcast', 'Podcast')], help_text='Type of resource', max_length=16),
        ),
        migrations.AlterField(
            model_name='guidanceresource',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Resource subtitle', max_length=160),
        ),
        migrations.AlterField(
            model_name='guidanceresource',
            name='summary',
            field=models.TextField(blank=True, help_text='Resource summary'),
        ),
        migrations.AlterField(
            model_name='guidanceresource',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='guidanceresource',
            name='title',
            field=models.CharField(help_text='Resource title', max_length=200),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Audio file URL'),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='category',
            field=models.CharField(help_text='Session category', max_length=60),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When session was created'),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='description',
            field=models.TextField(blank=True, help_text='Session description'),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Difficulty level', max_length=20),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Session duration in minutes'),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether session is featured'),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Session subtitle', max_length=160),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='title',
            field=models.CharField(help_text='Session title', max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When session was last updated'),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video file URL'),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='action_label',
            field=models.CharField(default='Start', help_text='Action button label', max_length=60),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='category',
            field=models.CharField(choices=[('breathing', 'Breathing'), ('audio', 'Audio'), ('movement', 'Movement'), ('reflection', 'Reflection')], default='breathing', help_text='Booster category', max_length=32),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When booster was created'),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='description',
            field=models.TextField(blank=True, help_text='Booster description'),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='estimated_seconds',
            field=models.PositiveIntegerField(default=120, help_text='Estimated duration in seconds'),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon identifier', max_length=40),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='prompt',
            field=models.TextField(blank=True, help_text='Booster prompt text'),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='resource_url',
            field=models.URLField(blank=True, help_text='Resource URL'),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Booster subtitle', max_length=160),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='title',
            field=models.CharField(help_text='Booster title', max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='mindcarebooster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When booster was last updated'),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When log was created'),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When mood was recorded'),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='user',
            field=models.ForeignKey(help_text='User who recorded this mood', on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='value',
            field=models.PositiveSmallIntegerField(help_text='Mood value (1-5 scale)'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Audio file URL'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When track was created'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='description',
            field=models.TextField(blank=True, help_text='Track description'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=180, help_text='Track duration in seconds'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='mood',
            field=models.CharField(choices=[('calm', 'Calm'), ('focus', 'Focus'), ('sleep', 'Sleep'), ('uplift', 'Uplift')], default='calm', help_text='Mood category', max_length=20),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Thumbnail URL'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='title',
            field=models.CharField(help_text='Track title', max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When track was last updated'),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When group was created'),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='description',
            field=models.TextField(blank=True, help_text='Group description'),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon identifier', max_length=64),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='name',
            field=models.CharField(help_text='Group name', max_length=160),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='slug',
            field=models.SlugField(help_text='Unique URL-friendly identifier', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='supportgroupmembership',
            name='group',
            field=models.ForeignKey(help_text='Support group', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.supportgroup'),
        ),
        migrations.AlterField(
            model_name='supportgroupmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When user joined the group'),
        ),
        migrations.AlterField(
            model_name='supportgroupmembership',
            name='user',
            field=models.ForeignKey(help_text='User who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='support_group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upcomingsession',
            name='counsellor',
            field=models.ForeignKey(blank=True, help_text='Counselor assigned to this session', limit_choices_to={'counsellorprofile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsellor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upcomingsession',
            name='counsellor_name',
            field=models.CharField(help_text='Name of the counselor', max_length=160),
        ),
        migrations.AlterField(
            model_name='upcomingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When session was created'),
        ),
        migrations.AlterField(
            model_name='upcomingsession',
            name='is_confirmed',
            field=models.BooleanField(default=True, help_text='Whether session is confirmed'),
        ),
        migrations.AlterField(
            model_name='upcomingsession',
            name='notes',
            field=models.TextField(blank=True, help_text='Session notes (start/end timestamps appended here)'),
        ),
        migrations.AlterField(
            model_name='upcomingsession',
            name='session_type',
            field=models.CharField(choices=[('one_on_one', 'One-on-One'), ('group', 'Group'), ('workshop', 'Workshop'), ('webinar', 'Webinar')], help_text='Type of session', max_length=40),
        ),
        migrations.AlterField(
            model_name='upcomingsession',
            name='start_time',
            field=models.DateTimeField(help_text='Scheduled start time'),
        ),
        migrations.AlterField(
            model_name='upcomingsession',
            name='title',
            field=models.CharField(help_text='Session title', max_length=180),
        ),
        migrations.AlterField(
            model_name='upcomingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When session was last updated'),
        ),
        migrations.AlterField(
            model_name='upcomingsession',
            name='user',
            field=models.ForeignKey(help_text='User who scheduled this session', on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text="User's age", null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When profile was created'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text="User's full name", max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, help_text="User's gender", max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='English', help_text='Preferred language', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_mood',
            field=models.PositiveSmallIntegerField(default=3, help_text='Last recorded mood value (1-5 scale)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_mood_updated',
            field=models.DateTimeField(blank=True, help_text='When mood was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mood_updates_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Total number of mood updates'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mood_updates_date',
            field=models.DateField(blank=True, help_text='Date of last mood update', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, help_text="User's preferred nickname", max_length=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prefers_dark_mode',
            field=models.BooleanField(default=False, help_text='Whether user prefers dark mode'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, help_text="User's timezone (e.g., 'Asia/Kolkata')", max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When profile was last updated'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Associated Django User', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_minutes',
            field=models.PositiveIntegerField(default=100, help_text='Available minutes in wallet for services'),
        ),
        migrations.AlterField(
            model_name='wellnessjournalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When entry was created'),
        ),
        migrations.AlterField(
            model_name='wellnessjournalentry',
            name='entry_type',
            field=models.CharField(choices=[('3-Day Journal', '3-Day Journal'), ('Weekly Journal', 'Weekly Journal'), ('Custom', 'Custom')], help_text='Type of journal entry', max_length=40),
        ),
        migrations.AlterField(
            model_name='wellnessjournalentry',
            name='mood',
            field=models.CharField(help_text='Mood at time of entry', max_length=16),
        ),
        migrations.AlterField(
            model_name='wellnessjournalentry',
            name='note',
            field=models.TextField(help_text='Journal entry content'),
        ),
        migrations.AlterField(
            model_name='wellnessjournalentry',
            name='title',
            field=models.CharField(help_text='Entry title', max_length=160),
        ),
        migrations.AlterField(
            model_name='wellnessjournalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When entry was last updated'),
        ),
        migrations.AlterField(
            model_name='wellnessjournalentry',
            name='user',
            field=models.ForeignKey(help_text='User who owns this journal entry', on_delete=django.db.models.deletion.CASCADE, related_name='wellness_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wellnesstask',
            name='category',
            field=models.CharField(choices=[('daily', 'Daily'), ('evening', 'Evening')], help_text='Task category', max_length=20),
        ),
        migrations.AlterField(
            model_name='wellnesstask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When task was created'),
        ),
        migrations.AlterField(
            model_name='wellnesstask',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether task is completed'),
        ),
        migrations.AlterField(
            model_name='wellnesstask',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='wellnesstask',
            name='title',
            field=models.CharField(help_text='Task title', max_length=150),
        ),
        migrations.AlterField(
            model_name='wellnesstask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When task was last updated'),
        ),
        migrations.AlterField(
            model_name='wellnesstask',
            name='user',
            field=models.ForeignKey(help_text='User who owns this task', on_delete=django.db.models.deletion.CASCADE, related_name='wellness_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['wallet_minutes'], name='api_userpro_wallet__a34a5f_idx'),
        ),
    ]
