# Generated by Django 5.2.8 on 2025-11-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_call_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_user_activity',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the user last interacted with this chat (sending message or opening chat)', null=True),
        ),
    ]
