# Generated by Django 4.2.7 on 2025-11-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_last_user_activity_to_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', help_text='Current status of the chat', max_length=20),
        ),
    ]
