# Generated by Django 4.2.7 on 2025-11-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_chat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingsession',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When session actually ended', null=True),
        ),
        migrations.AddField(
            model_name='upcomingsession',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When session actually started (not scheduled time)', null=True),
        ),
        migrations.AddField(
            model_name='upcomingsession',
            name='manual_flag',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', help_text='Manual flag set by counselor', max_length=10),
        ),
        migrations.AddField(
            model_name='upcomingsession',
            name='risk_level',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='none', help_text='Risk level assessment', max_length=20),
        ),
        migrations.AddField(
            model_name='upcomingsession',
            name='session_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', help_text='Current status of the session', max_length=20),
        ),
        migrations.AlterField(
            model_name='upcomingsession',
            name='notes',
            field=models.TextField(blank=True, help_text='Session notes (confidential notes for counselor)'),
        ),
        migrations.AddIndex(
            model_name='upcomingsession',
            index=models.Index(fields=['counsellor', 'session_status'], name='api_upcomin_counsel_d3aaf7_idx'),
        ),
        migrations.AddIndex(
            model_name='upcomingsession',
            index=models.Index(fields=['session_status', 'actual_start_time'], name='api_upcomin_session_230ebe_idx'),
        ),
    ]
