# Generated by Django 4.2.7 on 2025-11-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_upcomingsession_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='billed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount billed for this chat (in rupees)', max_digits=10),
        ),
        migrations.AddField(
            model_name='chat',
            name='billing_processed_at',
            field=models.DateTimeField(blank=True, help_text='When billing was processed', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Total active chat duration in minutes (for billing calculation)'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_billed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether billing has been processed and wallet deducted'),
        ),
    ]
